{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "import csv\n",
    "import numpy as np\n",
    "import pprint # as pp\n",
    "import operator\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "np.set_printoptions(precision=3)\n",
    "\n",
    "class FormatPrinter(pprint.PrettyPrinter):\n",
    "\n",
    "    def __init__(self, formats):\n",
    "        super(FormatPrinter, self).__init__()\n",
    "        self.formats = formats\n",
    "\n",
    "    def format(self, obj, ctx, maxlvl, lvl):\n",
    "        if type(obj) in self.formats:\n",
    "            return self.formats[type(obj)] % obj, 1, 0\n",
    "        return pprint.PrettyPrinter.format(self, obj, ctx, maxlvl, lvl)\n",
    "\n",
    "fp = FormatPrinter({float: \"%0.2f\", int: \"%d\"})\n",
    "    \n",
    "with open('/Users/matt/Downloads/logs/2020-12-12-first_chaos_full.csv', newline='') as csvfile:\n",
    "    spamreader = csv.reader(csvfile, delimiter=',', quotechar='|')\n",
    "    \n",
    "    allVotes = []\n",
    "    allNames = []\n",
    "    for row in spamreader:\n",
    "        row.pop(6)\n",
    "        names = np.array(row[::2])\n",
    "        votes = np.array(row[1::2]).astype(int)\n",
    "        \n",
    "        indices = votes[::-1].argsort()\n",
    "        names = names[::-1][indices]\n",
    "        votes = votes[::-1][indices]\n",
    "        if votes.sum() > 0:\n",
    "            allVotes.append(votes)\n",
    "            allNames.append(names)\n",
    "            percentages = votes.astype(float)/float(votes.sum())*100.0\n",
    "        else:\n",
    "            percentages = votes.astype(float)*100.0\n",
    "        #print(names)\n",
    "        #print(indices)\n",
    "        #print(sortedNames)\n",
    "        #print(sortedVotes)\n",
    "        #print(percentages)\n",
    "    \n",
    "    voteData = {}\n",
    "    for i in range(len(allNames)):\n",
    "        for k in range(len(allNames[i])):\n",
    "            key = allNames[i][k] #.replace(\" \",\"\").replace(\"/\",\"\")\n",
    "            #print(key)\n",
    "            if not key in voteData:\n",
    "                voteData[key] = {}\n",
    "                voteData[key]['totalVotes'] = 0\n",
    "                voteData[key]['totalWins'] = 0\n",
    "                voteData[key]['totalLosses'] = 0\n",
    "                voteData[key]['totalLast'] = 0\n",
    "                voteData[key]['totalAppearances'] = 0\n",
    "                voteData[key]['lostTo'] = {}\n",
    "\n",
    "            voteData[key]['totalVotes'] += allVotes[i][k]\n",
    "            \n",
    "    for key in voteData:\n",
    "        for votingRound in allNames:\n",
    "            if key in votingRound:\n",
    "                voteData[key]['totalAppearances'] += 1\n",
    "                if key == votingRound[0]:\n",
    "                    voteData[key]['totalLast'] += 1\n",
    "                \n",
    "                winningVote = votingRound[len(votingRound)-1]\n",
    "                if key == winningVote:\n",
    "                    voteData[key]['totalWins'] += 1\n",
    "                else:\n",
    "                    voteData[key]['totalLosses'] += 1\n",
    "                    if not winningVote in voteData[key]['lostTo']:\n",
    "                        voteData[key]['lostTo'][winningVote] = 0\n",
    "                    voteData[key]['lostTo'][winningVote] += 1\n",
    "                \n",
    "    for key in voteData:\n",
    "        voteData[key]['Win Percentage'] = voteData[key]['totalWins']/voteData[key]['totalAppearances']*100\n",
    "        voteData[key]['Last Percentage'] = voteData[key]['totalLast']/voteData[key]['totalAppearances']*100\n",
    "        voteData[key]['Popularity'] = voteData[key]['totalVotes']/voteData[key]['totalAppearances']\n",
    "    #pp.pprint(voteData)\n",
    "    \n",
    "def getHighestByKey(voteData, key, total, reverse=False):\n",
    "    sortedWins = list({k: v for k, v in sorted(voteData.items(), key=lambda item: item[1][key], reverse=reverse)})\n",
    "    top = []\n",
    "    for i in range(len(sortedWins)-total,len(sortedWins)):\n",
    "        top.append( (sortedWins[i], voteData[sortedWins[i]][key]) )\n",
    "    return top\n",
    "    \n",
    "  \n",
    "    \n",
    "    \n",
    "    \n",
    "    \n",
    "        "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Total number or options that appears: 92\n",
      "Total number of voted rounds: 379\n",
      "Average votes/round: 6.79\n",
      "Most voted round:\n",
      " 1: Swap Joysticks\n",
      " 1: Inverted\n",
      "10: Mirror World\n"
     ]
    }
   ],
   "source": [
    "print(\"Total number or options that appears: \" + str(len(voteData.keys())))\n",
    "print(\"Total number of voted rounds: \" + str(len(allVotes)))\n",
    "\n",
    "totalVotes = []\n",
    "for i in range(len(allVotes)):\n",
    "    totalVotes.append(sum(allVotes[i]))\n",
    "print(\"Average votes/round: %0.2f\" % (sum(totalVotes)/len(totalVotes)))\n",
    "\n",
    "index = np.argmax(np.array(totalVotes), axis=0)\n",
    "print(\"Most voted round:\")\n",
    "for i in range(len(allVotes[index])):\n",
    "    print(\"%2d: %s\" % (allVotes[index][i], allNames[index][i]))\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 213,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Top Wins: \n",
      "[('Controller Mirror', 69.23076923076923),\n",
      " ('Disable Right Joystick', 71.42857142857143),\n",
      " ('Helium Audio', 72.72727272727273),\n",
      " ('Swap Joysticks', 75.0),\n",
      " ('Drunk', 75.0),\n",
      " ('Keep Jumping', 78.57142857142857),\n",
      " ('Disco', 81.25),\n",
      " ('Toss A Molly', 83.33333333333334),\n",
      " ('Mirror World', 88.88888888888889),\n",
      " ('CTG Strat', 100.0)]\n"
     ]
    },
    {
     "ename": "NameError",
     "evalue": "name 'plt' is not defined",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mNameError\u001b[0m                                 Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-213-f1b8692067ff>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m      2\u001b[0m \u001b[0mprint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"Top Wins: \"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      3\u001b[0m \u001b[0mfp\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mpprint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mtopWins\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 4\u001b[0;31m \u001b[0mfig\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mplt\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mfigure\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      5\u001b[0m \u001b[0max\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mfig\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0madd_axes\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;36m0\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;36m0\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;36m1\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;36m1\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      6\u001b[0m \u001b[0mnames\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;34m[\u001b[0m\u001b[0mx\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;36m0\u001b[0m\u001b[0;34m]\u001b[0m \u001b[0;32mfor\u001b[0m \u001b[0mx\u001b[0m \u001b[0;32min\u001b[0m \u001b[0mtopWins\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mNameError\u001b[0m: name 'plt' is not defined"
     ]
    }
   ],
   "source": [
    "topWins = getHighestByKey(voteData, 'Win Percentage', 10)\n",
    "print(\"Top Wins: \")\n",
    "fp.pprint(topWins) \n",
    "fig = plt.figure()\n",
    "ax = fig.add_axes([0, 0, 1, 1])\n",
    "names = [x[0] for x in topWins]\n",
    "percent = [x[1] for x in topWins]\n",
    "ax.bar(names, percent)\n",
    "plt.show()\n",
    "\n",
    "topLasts = getHighestByKey(voteData, 'Last Percentage', 5)\n",
    "print(\"Top Lasts: \")\n",
    "fp.pprint(topLasts)\n",
    "\n",
    "topVotes = getHighestByKey(voteData, 'Popularity', 10, reverse=False)\n",
    "print(\"Popularity: \")\n",
    "fp.pprint(topVotes)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 169,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'1960': {'Last Percentage': 64.29,\n",
      "          'Popularity': 1.8571428571428572,\n",
      "          'Win Percentage': 14.29,\n",
      "          'lostTo': {'8-Bit Audio': 1,\n",
      "                     'Blacklight': 1,\n",
      "                     'Disable Right Joystick': 1,\n",
      "                     'Force Running': 1,\n",
      "                     'Inverted': 1,\n",
      "                     'No Aiming': 2,\n",
      "                     'No Reloading': 1,\n",
      "                     'Noir': 1,\n",
      "                     'Pdub It': 1,\n",
      "                     'Restart Checkpoint': 1,\n",
      "                     'Toss A Molly': 1},\n",
      "          'totalAppearances': 14,\n",
      "          'totalLast': 9,\n",
      "          'totalLosses': 12,\n",
      "          'totalVotes': 26,\n",
      "          'totalWins': 2},\n",
      " '4-Bit Audio': {'Last Percentage': 50.00,\n",
      "                 'Popularity': 1.9166666666666667,\n",
      "                 'Win Percentage': 25.00,\n",
      "                 'lostTo': {'CTG Strat': 1,\n",
      "                            'Disable Right Joystick': 2,\n",
      "                            'Gridlocked': 1,\n",
      "                            'High Contrast Display': 1,\n",
      "                            'Infinite Crafting': 1,\n",
      "                            'Mirror On Death': 1,\n",
      "                            'Moonlight': 1,\n",
      "                            'Toss A Molly': 1},\n",
      "                 'totalAppearances': 12,\n",
      "                 'totalLast': 6,\n",
      "                 'totalLosses': 9,\n",
      "                 'totalVotes': 23,\n",
      "                 'totalWins': 3},\n",
      " '8-Bit': {'Last Percentage': 25.00,\n",
      "           'Popularity': 2.9166666666666665,\n",
      "           'Win Percentage': 41.67,\n",
      "           'lostTo': {'Auto Pick-Up': 1,\n",
      "                      'Disable Right Joystick': 2,\n",
      "                      'Disco': 1,\n",
      "                      'Helium Audio': 1,\n",
      "                      'Keep Dodging': 1,\n",
      "                      'Keep Jumping': 1},\n",
      "           'totalAppearances': 12,\n",
      "           'totalLast': 3,\n",
      "           'totalLosses': 7,\n",
      "           'totalVotes': 35,\n",
      "           'totalWins': 5},\n",
      " '8-Bit Audio': {'Last Percentage': 26.32,\n",
      "                 'Popularity': 2.3684210526315788,\n",
      "                 'Win Percentage': 26.32,\n",
      "                 'lostTo': {'8-Bit': 1,\n",
      "                            'Afterlife': 1,\n",
      "                            'Blood': 1,\n",
      "                            'Force Running': 1,\n",
      "                            'Helium Audio': 1,\n",
      "                            'Keep Jumping': 1,\n",
      "                            'Melee Only': 1,\n",
      "                            'Mirror World': 1,\n",
      "                            'No Melee': 1,\n",
      "                            'No Triangle': 1,\n",
      "                            'Pdub It': 1,\n",
      "                            'Restart Checkpoint': 1,\n",
      "                            'Slow Motion': 1,\n",
      "                            'Water Color': 1},\n",
      "                 'totalAppearances': 19,\n",
      "                 'totalLast': 5,\n",
      "                 'totalLosses': 14,\n",
      "                 'totalVotes': 45,\n",
      "                 'totalWins': 5},\n",
      " 'Afterlife': {'Last Percentage': 33.33,\n",
      "               'Popularity': 1.8888888888888888,\n",
      "               'Win Percentage': 33.33,\n",
      "               'lostTo': {'Disco': 1,\n",
      "                          'Keep Dodging': 1,\n",
      "                          'Keep Jumping': 1,\n",
      "                          'No Crouch/Prone': 1,\n",
      "                          'Restart Checkpoint': 1,\n",
      "                          'Swap Joysticks': 1},\n",
      "               'totalAppearances': 9,\n",
      "               'totalLast': 3,\n",
      "               'totalLosses': 6,\n",
      "               'totalVotes': 17,\n",
      "               'totalWins': 3},\n",
      " 'Auto Pick-Up': {'Last Percentage': 41.67,\n",
      "                  'Popularity': 1.4166666666666667,\n",
      "                  'Win Percentage': 16.67,\n",
      "                  'lostTo': {'8-Bit': 2,\n",
      "                             'Bullet Speed': 1,\n",
      "                             'CTG Strat': 2,\n",
      "                             'Keep Jumping': 1,\n",
      "                             'Large HUD': 1,\n",
      "                             'Max Sensitivity': 1,\n",
      "                             'Nascar': 1,\n",
      "                             'No Crouch/Prone': 1},\n",
      "                  'totalAppearances': 12,\n",
      "                  'totalLast': 5,\n",
      "                  'totalLosses': 10,\n",
      "                  'totalVotes': 17,\n",
      "                  'totalWins': 2},\n",
      " 'Beasts': {'Last Percentage': 16.67,\n",
      "            'Popularity': 3.6666666666666665,\n",
      "            'Win Percentage': 50.00,\n",
      "            'lostTo': {'Drunk': 1, 'Dungeon': 1, 'Rachy Flail': 1},\n",
      "            'totalAppearances': 6,\n",
      "            'totalLast': 1,\n",
      "            'totalLosses': 3,\n",
      "            'totalVotes': 22,\n",
      "            'totalWins': 3},\n",
      " 'Blacklight': {'Last Percentage': 20.00,\n",
      "                'Popularity': 2.9,\n",
      "                'Win Percentage': 60.00,\n",
      "                'lostTo': {'8-Bit': 2, 'Terminated': 2},\n",
      "                'totalAppearances': 10,\n",
      "                'totalLast': 2,\n",
      "                'totalLosses': 4,\n",
      "                'totalVotes': 29,\n",
      "                'totalWins': 6},\n",
      " 'Blood': {'Last Percentage': 40.00,\n",
      "           'Popularity': 2.3,\n",
      "           'Win Percentage': 20.00,\n",
      "           'lostTo': {'CTG Strat': 1,\n",
      "                      'Helium Audio': 1,\n",
      "                      'Infinite Crafting': 1,\n",
      "                      'No Crouch/Prone': 1,\n",
      "                      'Pdub It': 1,\n",
      "                      'Periodic Listen Mode': 1,\n",
      "                      'Swap Joysticks': 1,\n",
      "                      'Toss A Molly': 1},\n",
      "           'totalAppearances': 10,\n",
      "           'totalLast': 4,\n",
      "           'totalLosses': 8,\n",
      "           'totalVotes': 23,\n",
      "           'totalWins': 2},\n",
      " 'Blorange': {'Last Percentage': 25.00,\n",
      "              'Popularity': 2.75,\n",
      "              'Win Percentage': 50.00,\n",
      "              'lostTo': {'Keep Jumping': 1, 'Noir': 1},\n",
      "              'totalAppearances': 4,\n",
      "              'totalLast': 1,\n",
      "              'totalLosses': 2,\n",
      "              'totalVotes': 11,\n",
      "              'totalWins': 2},\n",
      " 'Bullet Speed': {'Last Percentage': 12.50,\n",
      "                  'Popularity': 3.5625,\n",
      "                  'Win Percentage': 43.75,\n",
      "                  'lostTo': {'8-Bit': 1,\n",
      "                             'CTG Strat': 1,\n",
      "                             'Infinite Crafting': 1,\n",
      "                             'Lock On Aim': 1,\n",
      "                             'Nascar': 1,\n",
      "                             'No Crouch/Prone': 1,\n",
      "                             'No Triangle': 1,\n",
      "                             'Swap Joysticks': 1,\n",
      "                             'Terminated': 1},\n",
      "                  'totalAppearances': 16,\n",
      "                  'totalLast': 2,\n",
      "                  'totalLosses': 9,\n",
      "                  'totalVotes': 57,\n",
      "                  'totalWins': 7},\n",
      " 'CTG Strat': {'Last Percentage': 0.00,\n",
      "               'Popularity': 5.909090909090909,\n",
      "               'Win Percentage': 100.00,\n",
      "               'lostTo': {},\n",
      "               'totalAppearances': 11,\n",
      "               'totalLast': 0,\n",
      "               'totalLosses': 0,\n",
      "               'totalVotes': 65,\n",
      "               'totalWins': 11},\n",
      " 'Chuck Smoke Bomb': {'Last Percentage': 18.18,\n",
      "                      'Popularity': 3.909090909090909,\n",
      "                      'Win Percentage': 54.55,\n",
      "                      'lostTo': {'1960': 1,\n",
      "                                 'Keep Jumping': 1,\n",
      "                                 'Mirror World': 1,\n",
      "                                 'No Climbing/Jumping': 1,\n",
      "                                 'No Guns': 1},\n",
      "                      'totalAppearances': 11,\n",
      "                      'totalLast': 2,\n",
      "                      'totalLosses': 5,\n",
      "                      'totalVotes': 43,\n",
      "                      'totalWins': 6},\n",
      " 'Combat Audio Cues': {'Last Percentage': 83.33,\n",
      "                       'Popularity': 0.3333333333333333,\n",
      "                       'Win Percentage': 0.00,\n",
      "                       'lostTo': {'4-Bit Audio': 1,\n",
      "                                  'Desk Pop': 1,\n",
      "                                  'Force Running': 1,\n",
      "                                  'Infinite Crafting': 1,\n",
      "                                  'No Reticle': 1,\n",
      "                                  'No Throwables': 1},\n",
      "                       'totalAppearances': 6,\n",
      "                       'totalLast': 5,\n",
      "                       'totalLosses': 6,\n",
      "                       'totalVotes': 2,\n",
      "                       'totalWins': 0},\n",
      " 'Controller Mirror': {'Last Percentage': 0.00,\n",
      "                       'Popularity': 3.769230769230769,\n",
      "                       'Win Percentage': 69.23,\n",
      "                       'lostTo': {'CTG Strat': 1,\n",
      "                                  'Infinite Ammo': 1,\n",
      "                                  'Large HUD': 1,\n",
      "                                  'Pop Poster': 1},\n",
      "                       'totalAppearances': 13,\n",
      "                       'totalLast': 0,\n",
      "                       'totalLosses': 4,\n",
      "                       'totalVotes': 49,\n",
      "                       'totalWins': 9},\n",
      " 'Cool': {'Last Percentage': 52.94,\n",
      "          'Popularity': 1.0588235294117647,\n",
      "          'Win Percentage': 5.88,\n",
      "          'lostTo': {'4-Bit Audio': 1,\n",
      "                     '8-Bit Audio': 1,\n",
      "                     'Blacklight': 1,\n",
      "                     'Chuck Smoke Bomb': 1,\n",
      "                     'Disco': 1,\n",
      "                     'Drunk': 1,\n",
      "                     'Force Running': 1,\n",
      "                     'Helium Audio': 1,\n",
      "                     'Infinite Breath': 1,\n",
      "                     'Keep Dodging': 1,\n",
      "                     'Keep Jumping': 1,\n",
      "                     'Melee Only': 1,\n",
      "                     'No Throwables': 1,\n",
      "                     'One Shot': 1,\n",
      "                     'Terminated': 1,\n",
      "                     'Trinity': 1},\n",
      "          'totalAppearances': 17,\n",
      "          'totalLast': 9,\n",
      "          'totalLosses': 16,\n",
      "          'totalVotes': 18,\n",
      "          'totalWins': 1},\n",
      " 'Demons': {'Last Percentage': 25.00,\n",
      "            'Popularity': 1.6666666666666667,\n",
      "            'Win Percentage': 8.33,\n",
      "            'lostTo': {'Beasts': 1,\n",
      "                       'Bullet Speed': 1,\n",
      "                       'Controller Mirror': 1,\n",
      "                       'Drunk': 1,\n",
      "                       'High Contrast Display': 1,\n",
      "                       'Inverted': 1,\n",
      "                       'Moonlight': 2,\n",
      "                       'Nascar': 1,\n",
      "                       'Noir': 1,\n",
      "                       'Rachy Flail': 1},\n",
      "            'totalAppearances': 12,\n",
      "            'totalLast': 3,\n",
      "            'totalLosses': 11,\n",
      "            'totalVotes': 20,\n",
      "            'totalWins': 1},\n",
      " 'Desert Fog': {'Last Percentage': 37.50,\n",
      "                'Popularity': 1.5625,\n",
      "                'Win Percentage': 6.25,\n",
      "                'lostTo': {'4-Bit Audio': 1,\n",
      "                           'Afterlife': 1,\n",
      "                           'CTG Strat': 2,\n",
      "                           'Controller Mirror': 1,\n",
      "                           'Drunk': 2,\n",
      "                           'Keep Jumping': 1,\n",
      "                           'No Crouch/Prone': 1,\n",
      "                           'No Reloading': 1,\n",
      "                           'No Reticle': 1,\n",
      "                           'No Throwables': 1,\n",
      "                           'No Triangle': 1,\n",
      "                           'Pop Poster': 1,\n",
      "                           'Xenon Audio': 1},\n",
      "                'totalAppearances': 16,\n",
      "                'totalLast': 6,\n",
      "                'totalLosses': 15,\n",
      "                'totalVotes': 25,\n",
      "                'totalWins': 1},\n",
      " 'Desk Pop': {'Last Percentage': 7.69,\n",
      "              'Popularity': 2.3076923076923075,\n",
      "              'Win Percentage': 46.15,\n",
      "              'lostTo': {'Disable Right Joystick': 2,\n",
      "                         'Force Running': 1,\n",
      "                         'Max Sensitivity': 1,\n",
      "                         'Mirror On Death': 1,\n",
      "                         'Moonlight': 1,\n",
      "                         'No Climbing/Jumping': 1},\n",
      "              'totalAppearances': 13,\n",
      "              'totalLast': 1,\n",
      "              'totalLosses': 7,\n",
      "              'totalVotes': 30,\n",
      "              'totalWins': 6},\n",
      " 'Disable Right Joystick': {'Last Percentage': 14.29,\n",
      "                            'Popularity': 3.9285714285714284,\n",
      "                            'Win Percentage': 71.43,\n",
      "                            'lostTo': {'Fire': 1,\n",
      "                                       'Helium Audio': 1,\n",
      "                                       'No Triangle': 1,\n",
      "                                       'Swap Joysticks': 1},\n",
      "                            'totalAppearances': 14,\n",
      "                            'totalLast': 2,\n",
      "                            'totalLosses': 4,\n",
      "                            'totalVotes': 55,\n",
      "                            'totalWins': 10},\n",
      " 'Disco': {'Last Percentage': 6.25,\n",
      "           'Popularity': 3.3125,\n",
      "           'Win Percentage': 81.25,\n",
      "           'lostTo': {'High Contrast Display': 1,\n",
      "                      'No Crouch/Prone': 1,\n",
      "                      'No Guns': 1},\n",
      "           'totalAppearances': 16,\n",
      "           'totalLast': 1,\n",
      "           'totalLosses': 3,\n",
      "           'totalVotes': 53,\n",
      "           'totalWins': 13},\n",
      " 'Drug Zone': {'Last Percentage': 41.67,\n",
      "               'Popularity': 2.0,\n",
      "               'Win Percentage': 25.00,\n",
      "               'lostTo': {'Desk Pop': 1,\n",
      "                          'Force Prone': 2,\n",
      "                          'Keep Dodging': 1,\n",
      "                          'Pop Poster': 1,\n",
      "                          'Rachy Flail': 1,\n",
      "                          'Swap Joysticks': 1,\n",
      "                          'Terminated': 1,\n",
      "                          'Void': 1},\n",
      "               'totalAppearances': 12,\n",
      "               'totalLast': 5,\n",
      "               'totalLosses': 9,\n",
      "               'totalVotes': 24,\n",
      "               'totalWins': 3},\n",
      " 'Drunk': {'Last Percentage': 0.00,\n",
      "           'Popularity': 4.5,\n",
      "           'Win Percentage': 75.00,\n",
      "           'lostTo': {'Blacklight': 1,\n",
      "                      'Controller Mirror': 1,\n",
      "                      'Infinite Crafting': 1},\n",
      "           'totalAppearances': 12,\n",
      "           'totalLast': 0,\n",
      "           'totalLosses': 3,\n",
      "           'totalVotes': 54,\n",
      "           'totalWins': 9},\n",
      " 'Dungeon': {'Last Percentage': 25.00,\n",
      "             'Popularity': 2.0,\n",
      "             'Win Percentage': 25.00,\n",
      "             'lostTo': {'Blorange': 1,\n",
      "                        'Fire': 1,\n",
      "                        'Force Running': 1,\n",
      "                        'No Reloading': 1,\n",
      "                        'Rachy Flail': 1,\n",
      "                        'Toss A Molly': 1},\n",
      "             'totalAppearances': 8,\n",
      "             'totalLast': 2,\n",
      "             'totalLosses': 6,\n",
      "             'totalVotes': 16,\n",
      "             'totalWins': 2},\n",
      " \"Enemies Don't Flank\": {'Last Percentage': 73.68,\n",
      "                         'Popularity': 0.5263157894736842,\n",
      "                         'Win Percentage': 0.00,\n",
      "                         'lostTo': {'Beasts': 1,\n",
      "                                    'Blacklight': 1,\n",
      "                                    'Blood': 1,\n",
      "                                    'CTG Strat': 1,\n",
      "                                    'Desk Pop': 1,\n",
      "                                    'Disco': 1,\n",
      "                                    'Drug Zone': 1,\n",
      "                                    'Force Running': 1,\n",
      "                                    'Gridlocked': 1,\n",
      "                                    'High Contrast Display': 1,\n",
      "                                    'Max Sensitivity': 1,\n",
      "                                    'Melee Only': 1,\n",
      "                                    'Mirror On Death': 1,\n",
      "                                    'No Climbing/Jumping': 1,\n",
      "                                    'Noir': 1,\n",
      "                                    'One Shot': 1,\n",
      "                                    'Pdub It': 1,\n",
      "                                    'Sepia': 1,\n",
      "                                    'Slow Motion': 1},\n",
      "                         'totalAppearances': 19,\n",
      "                         'totalLast': 14,\n",
      "                         'totalLosses': 19,\n",
      "                         'totalVotes': 10,\n",
      "                         'totalWins': 0},\n",
      " 'Enhanced Dodge': {'Last Percentage': 42.86,\n",
      "                    'Popularity': 0.8571428571428571,\n",
      "                    'Win Percentage': 0.00,\n",
      "                    'lostTo': {'8-Bit Audio': 1,\n",
      "                               'Force Prone': 1,\n",
      "                               'Headache': 1,\n",
      "                               'Infinite Ammo': 1,\n",
      "                               'Nascar': 1,\n",
      "                               'Swap Joysticks': 1,\n",
      "                               'Terminated': 1},\n",
      "                    'totalAppearances': 7,\n",
      "                    'totalLast': 3,\n",
      "                    'totalLosses': 7,\n",
      "                    'totalVotes': 6,\n",
      "                    'totalWins': 0},\n",
      " 'Enhanced Listen Mode': {'Last Percentage': 57.89,\n",
      "                          'Popularity': 0.7368421052631579,\n",
      "                          'Win Percentage': 0.00,\n",
      "                          'lostTo': {'Disable Right Joystick': 1,\n",
      "                                     'Disco': 3,\n",
      "                                     'Drug Zone': 1,\n",
      "                                     'Force Running': 2,\n",
      "                                     'Inferno': 1,\n",
      "                                     'Infinite Ammo': 1,\n",
      "                                     'Keep Dodging': 1,\n",
      "                                     'Keep Jumping': 2,\n",
      "                                     'Lock On Aim': 1,\n",
      "                                     'Mega Scope Sway': 1,\n",
      "                                     'No Crouch/Prone': 1,\n",
      "                                     'No Reloading': 1,\n",
      "                                     'Periodic Listen Mode': 1,\n",
      "                                     'Vibrant': 1,\n",
      "                                     'Void': 1},\n",
      "                          'totalAppearances': 19,\n",
      "                          'totalLast': 11,\n",
      "                          'totalLosses': 19,\n",
      "                          'totalVotes': 14,\n",
      "                          'totalWins': 0},\n",
      " 'Fire': {'Last Percentage': 28.57,\n",
      "          'Popularity': 1.6428571428571428,\n",
      "          'Win Percentage': 21.43,\n",
      "          'lostTo': {'Disable Right Joystick': 1,\n",
      "                     'Infinite Crafting': 1,\n",
      "                     'Inverted': 1,\n",
      "                     'Keep Jumping': 1,\n",
      "                     'Mirror On Death': 1,\n",
      "                     'Mirror World': 1,\n",
      "                     'No Reticle': 1,\n",
      "                     'Periodic Listen Mode': 1,\n",
      "                     'Rachy Flail': 1,\n",
      "                     'Swap Joysticks': 1,\n",
      "                     'Touch Of Death': 1},\n",
      "          'totalAppearances': 14,\n",
      "          'totalLast': 4,\n",
      "          'totalLosses': 11,\n",
      "          'totalVotes': 23,\n",
      "          'totalWins': 3},\n",
      " 'Force Prone': {'Last Percentage': 15.38,\n",
      "                 'Popularity': 3.6153846153846154,\n",
      "                 'Win Percentage': 38.46,\n",
      "                 'lostTo': {'Controller Mirror': 2,\n",
      "                            'Drunk': 1,\n",
      "                            'Melee Only': 1,\n",
      "                            'No Crouch/Prone': 1,\n",
      "                            'No Guns': 1,\n",
      "                            'No Reloading': 1,\n",
      "                            'Touch Of Death': 1},\n",
      "                 'totalAppearances': 13,\n",
      "                 'totalLast': 2,\n",
      "                 'totalLosses': 8,\n",
      "                 'totalVotes': 47,\n",
      "                 'totalWins': 5},\n",
      " 'Force Running': {'Last Percentage': 26.67,\n",
      "                   'Popularity': 2.533333333333333,\n",
      "                   'Win Percentage': 46.67,\n",
      "                   'lostTo': {'CTG Strat': 1,\n",
      "                              'Disable Right Joystick': 1,\n",
      "                              'Drunk': 1,\n",
      "                              'Fire': 1,\n",
      "                              'Helium Audio': 1,\n",
      "                              'Mirror World': 1,\n",
      "                              'No Reloading': 1,\n",
      "                              'Warm': 1},\n",
      "                   'totalAppearances': 15,\n",
      "                   'totalLast': 4,\n",
      "                   'totalLosses': 8,\n",
      "                   'totalVotes': 38,\n",
      "                   'totalWins': 7},\n",
      " 'Graphic': {'Last Percentage': 44.44,\n",
      "             'Popularity': 1.6666666666666667,\n",
      "             'Win Percentage': 33.33,\n",
      "             'lostTo': {'Disable Right Joystick': 1,\n",
      "                        'Keep Jumping': 1,\n",
      "                        'Mega Scope Sway': 2,\n",
      "                        'Noir': 1,\n",
      "                        'Terminated': 1},\n",
      "             'totalAppearances': 9,\n",
      "             'totalLast': 4,\n",
      "             'totalLosses': 6,\n",
      "             'totalVotes': 15,\n",
      "             'totalWins': 3},\n",
      " 'Gridlocked': {'Last Percentage': 45.45,\n",
      "                'Popularity': 1.5454545454545454,\n",
      "                'Win Percentage': 27.27,\n",
      "                'lostTo': {'Demons': 1,\n",
      "                           'Inverted': 1,\n",
      "                           'Keep Dodging': 1,\n",
      "                           'Max Sensitivity': 1,\n",
      "                           'No Climbing/Jumping': 1,\n",
      "                           'No Crouch/Prone': 1,\n",
      "                           'Periodic Listen Mode': 1,\n",
      "                           'Pop Poster': 1},\n",
      "                'totalAppearances': 11,\n",
      "                'totalLast': 5,\n",
      "                'totalLosses': 8,\n",
      "                'totalVotes': 17,\n",
      "                'totalWins': 3},\n",
      " 'Headache': {'Last Percentage': 41.67,\n",
      "              'Popularity': 2.4166666666666665,\n",
      "              'Win Percentage': 33.33,\n",
      "              'lostTo': {'Disco': 1,\n",
      "                         'Force Prone': 1,\n",
      "                         'Helium Audio': 1,\n",
      "                         'Max Sensitivity': 1,\n",
      "                         'No Aiming': 2,\n",
      "                         'Noir': 1,\n",
      "                         'Rachy Flail': 1},\n",
      "              'totalAppearances': 12,\n",
      "              'totalLast': 5,\n",
      "              'totalLosses': 8,\n",
      "              'totalVotes': 29,\n",
      "              'totalWins': 4},\n",
      " 'Helium Audio': {'Last Percentage': 9.09,\n",
      "                  'Popularity': 3.6363636363636362,\n",
      "                  'Win Percentage': 72.73,\n",
      "                  'lostTo': {'Controller Mirror': 1,\n",
      "                             'Drunk': 1,\n",
      "                             'Infinite Ammo': 1},\n",
      "                  'totalAppearances': 11,\n",
      "                  'totalLast': 1,\n",
      "                  'totalLosses': 3,\n",
      "                  'totalVotes': 40,\n",
      "                  'totalWins': 8},\n",
      " 'High Contrast Display': {'Last Percentage': 30.77,\n",
      "                           'Popularity': 2.230769230769231,\n",
      "                           'Win Percentage': 30.77,\n",
      "                           'lostTo': {'Beasts': 1,\n",
      "                                      'Bullet Speed': 1,\n",
      "                                      'Desk Pop': 1,\n",
      "                                      'Drunk': 1,\n",
      "                                      'Moonlight': 1,\n",
      "                                      'Nascar': 1,\n",
      "                                      'No Crouch/Prone': 1,\n",
      "                                      'No Reloading': 1,\n",
      "                                      'No Triangle': 1},\n",
      "                           'totalAppearances': 13,\n",
      "                           'totalLast': 4,\n",
      "                           'totalLosses': 9,\n",
      "                           'totalVotes': 29,\n",
      "                           'totalWins': 4},\n",
      " \"Hostage Don't Escape\": {'Last Percentage': 100.00,\n",
      "                          'Popularity': 0.5,\n",
      "                          'Win Percentage': 0.00,\n",
      "                          'lostTo': {'Bullet Speed': 1,\n",
      "                                     'CTG Strat': 1,\n",
      "                                     'Chuck Smoke Bomb': 1,\n",
      "                                     'Inverted': 1,\n",
      "                                     'No Crouch/Prone': 1,\n",
      "                                     'One Shot': 1,\n",
      "                                     'Rachy Flail': 1,\n",
      "                                     'Trinity': 1},\n",
      "                          'totalAppearances': 8,\n",
      "                          'totalLast': 8,\n",
      "                          'totalLosses': 8,\n",
      "                          'totalVotes': 4,\n",
      "                          'totalWins': 0},\n",
      " 'Inferno': {'Last Percentage': 47.37,\n",
      "             'Popularity': 2.0,\n",
      "             'Win Percentage': 15.79,\n",
      "             'lostTo': {'Afterlife': 1,\n",
      "                        'Controller Mirror': 1,\n",
      "                        'Demons': 1,\n",
      "                        'Desert Fog': 1,\n",
      "                        'Drug Zone': 1,\n",
      "                        'Fire': 1,\n",
      "                        'Headache': 1,\n",
      "                        'Keep Dodging': 1,\n",
      "                        'Max Sensitivity': 1,\n",
      "                        'Mirror World': 2,\n",
      "                        'No Reloading': 2,\n",
      "                        'Pdub It': 1,\n",
      "                        'Reduced Enemy Accuracy': 1,\n",
      "                        'Trinity': 1},\n",
      "             'totalAppearances': 19,\n",
      "             'totalLast': 9,\n",
      "             'totalLosses': 16,\n",
      "             'totalVotes': 38,\n",
      "             'totalWins': 3},\n",
      " 'Infinite Ammo': {'Last Percentage': 25.00,\n",
      "                   'Popularity': 2.1875,\n",
      "                   'Win Percentage': 43.75,\n",
      "                   'lostTo': {'8-Bit Audio': 1,\n",
      "                              'Disco': 1,\n",
      "                              'Force Running': 1,\n",
      "                              'Gridlocked': 1,\n",
      "                              'Keep Dodging': 1,\n",
      "                              'Moonlight': 1,\n",
      "                              'Noir': 1,\n",
      "                              'Vibrant': 1,\n",
      "                              'Xenon Audio': 1},\n",
      "                   'totalAppearances': 16,\n",
      "                   'totalLast': 4,\n",
      "                   'totalLosses': 9,\n",
      "                   'totalVotes': 35,\n",
      "                   'totalWins': 7},\n",
      " 'Infinite Breath': {'Last Percentage': 61.54,\n",
      "                     'Popularity': 1.1538461538461537,\n",
      "                     'Win Percentage': 7.69,\n",
      "                     'lostTo': {'Beasts': 1,\n",
      "                                'Blood': 1,\n",
      "                                'Blorange': 1,\n",
      "                                'Chuck Smoke Bomb': 1,\n",
      "                                'Cool': 1,\n",
      "                                'Disco': 2,\n",
      "                                'Graphic': 1,\n",
      "                                'Moonlight': 1,\n",
      "                                'No Reloading': 1,\n",
      "                                'Pusher': 1,\n",
      "                                'Vintage': 1},\n",
      "                     'totalAppearances': 13,\n",
      "                     'totalLast': 8,\n",
      "                     'totalLosses': 12,\n",
      "                     'totalVotes': 15,\n",
      "                     'totalWins': 1},\n",
      " 'Infinite Crafting': {'Last Percentage': 27.27,\n",
      "                       'Popularity': 2.5454545454545454,\n",
      "                       'Win Percentage': 45.45,\n",
      "                       'lostTo': {'Cool': 1,\n",
      "                                  'Drunk': 1,\n",
      "                                  'Graphic': 1,\n",
      "                                  'Infinite Ammo': 1,\n",
      "                                  'Pdub It': 1,\n",
      "                                  'Periodic Listen Mode': 1},\n",
      "                       'totalAppearances': 11,\n",
      "                       'totalLast': 3,\n",
      "                       'totalLosses': 6,\n",
      "                       'totalVotes': 28,\n",
      "                       'totalWins': 5},\n",
      " 'Infinite Listen Range': {'Last Percentage': 41.67,\n",
      "                           'Popularity': 0.5,\n",
      "                           'Win Percentage': 0.00,\n",
      "                           'lostTo': {'8-Bit': 1,\n",
      "                                      '8-Bit Audio': 1,\n",
      "                                      'Controller Mirror': 2,\n",
      "                                      'Disable Right Joystick': 1,\n",
      "                                      'Large HUD': 1,\n",
      "                                      'No Crouch/Prone': 2,\n",
      "                                      'No Throwables': 1,\n",
      "                                      'Restart Checkpoint': 1,\n",
      "                                      'Trinity': 1,\n",
      "                                      'Xenon Audio': 1},\n",
      "                           'totalAppearances': 12,\n",
      "                           'totalLast': 5,\n",
      "                           'totalLosses': 12,\n",
      "                           'totalVotes': 6,\n",
      "                           'totalWins': 0},\n",
      " 'Infinite Melee Durability': {'Last Percentage': 73.33,\n",
      "                               'Popularity': 0.6666666666666666,\n",
      "                               'Win Percentage': 0.00,\n",
      "                               'lostTo': {'8-Bit Audio': 1,\n",
      "                                          'Blacklight': 1,\n",
      "                                          'Bullet Speed': 1,\n",
      "                                          'CTG Strat': 1,\n",
      "                                          'Chuck Smoke Bomb': 1,\n",
      "                                          'Controller Mirror': 1,\n",
      "                                          'Drug Zone': 1,\n",
      "                                          'Force Prone': 1,\n",
      "                                          'Helium Audio': 1,\n",
      "                                          'Melee Only': 1,\n",
      "                                          'No Guns': 1,\n",
      "                                          'No Reticle': 1,\n",
      "                                          'Pdub It': 1,\n",
      "                                          'Sepia': 1,\n",
      "                                          'Trinity': 1},\n",
      "                               'totalAppearances': 15,\n",
      "                               'totalLast': 11,\n",
      "                               'totalLosses': 15,\n",
      "                               'totalVotes': 10,\n",
      "                               'totalWins': 0},\n",
      " 'Inverted': {'Last Percentage': 0.00,\n",
      "              'Popularity': 3.1818181818181817,\n",
      "              'Win Percentage': 63.64,\n",
      "              'lostTo': {'Mirror World': 1,\n",
      "                         'Nascar': 1,\n",
      "                         'Noir': 1,\n",
      "                         'Touch Of Death': 1},\n",
      "              'totalAppearances': 11,\n",
      "              'totalLast': 0,\n",
      "              'totalLosses': 4,\n",
      "              'totalVotes': 35,\n",
      "              'totalWins': 7},\n",
      " 'Invisible While Prone': {'Last Percentage': 44.44,\n",
      "                           'Popularity': 0.8888888888888888,\n",
      "                           'Win Percentage': 0.00,\n",
      "                           'lostTo': {'Chuck Smoke Bomb': 1,\n",
      "                                      'Disco': 1,\n",
      "                                      'Drug Zone': 1,\n",
      "                                      'Force Prone': 1,\n",
      "                                      'Graphic': 1,\n",
      "                                      'Helium Audio': 1,\n",
      "                                      'Large HUD': 1,\n",
      "                                      'Mirror World': 1,\n",
      "                                      'No Reticle': 1},\n",
      "                           'totalAppearances': 9,\n",
      "                           'totalLast': 4,\n",
      "                           'totalLosses': 9,\n",
      "                           'totalVotes': 8,\n",
      "                           'totalWins': 0},\n",
      " 'Keep Dodging': {'Last Percentage': 21.43,\n",
      "                  'Popularity': 2.4285714285714284,\n",
      "                  'Win Percentage': 50.00,\n",
      "                  'lostTo': {'CTG Strat': 1,\n",
      "                             'Disco': 1,\n",
      "                             'Nascar': 1,\n",
      "                             'No Guns': 1,\n",
      "                             'No Throwables': 1,\n",
      "                             'Pop Poster': 1,\n",
      "                             'Swap Joysticks': 1},\n",
      "                  'totalAppearances': 14,\n",
      "                  'totalLast': 3,\n",
      "                  'totalLosses': 7,\n",
      "                  'totalVotes': 34,\n",
      "                  'totalWins': 7},\n",
      " 'Keep Jumping': {'Last Percentage': 0.00,\n",
      "                  'Popularity': 4.642857142857143,\n",
      "                  'Win Percentage': 78.57,\n",
      "                  'lostTo': {'CTG Strat': 1,\n",
      "                             'Slow Motion': 1,\n",
      "                             'Touch Of Death': 1},\n",
      "                  'totalAppearances': 14,\n",
      "                  'totalLast': 0,\n",
      "                  'totalLosses': 3,\n",
      "                  'totalVotes': 65,\n",
      "                  'totalWins': 11},\n",
      " 'Large HUD': {'Last Percentage': 42.86,\n",
      "               'Popularity': 1.7142857142857142,\n",
      "               'Win Percentage': 28.57,\n",
      "               'lostTo': {'1960': 1,\n",
      "                          '4-Bit Audio': 1,\n",
      "                          'Dungeon': 1,\n",
      "                          'Keep Jumping': 1,\n",
      "                          'Melee Only': 1,\n",
      "                          'Nascar': 1,\n",
      "                          'No Climbing/Jumping': 1,\n",
      "                          'Periodic Listen Mode': 2,\n",
      "                          'Pop Poster': 1},\n",
      "               'totalAppearances': 14,\n",
      "               'totalLast': 6,\n",
      "               'totalLosses': 10,\n",
      "               'totalVotes': 24,\n",
      "               'totalWins': 4},\n",
      " 'Lock On Aim': {'Last Percentage': 33.33,\n",
      "                 'Popularity': 1.7777777777777777,\n",
      "                 'Win Percentage': 33.33,\n",
      "                 'lostTo': {'Keep Jumping': 1,\n",
      "                            'Melee Only': 1,\n",
      "                            'No Run/Dodge': 1,\n",
      "                            'No Triangle': 1,\n",
      "                            'Swap Joysticks': 1,\n",
      "                            'Vibrant': 1},\n",
      "                 'totalAppearances': 9,\n",
      "                 'totalLast': 3,\n",
      "                 'totalLosses': 6,\n",
      "                 'totalVotes': 16,\n",
      "                 'totalWins': 3},\n",
      " 'Max Sensitivity': {'Last Percentage': 25.00,\n",
      "                     'Popularity': 2.75,\n",
      "                     'Win Percentage': 33.33,\n",
      "                     'lostTo': {'CTG Strat': 1,\n",
      "                                'Disco': 1,\n",
      "                                'Drunk': 1,\n",
      "                                'Infinite Ammo': 1,\n",
      "                                'Keep Dodging': 1,\n",
      "                                'No Aiming': 1,\n",
      "                                'Pdub It': 1,\n",
      "                                'Pusher': 1},\n",
      "                     'totalAppearances': 12,\n",
      "                     'totalLast': 3,\n",
      "                     'totalLosses': 8,\n",
      "                     'totalVotes': 33,\n",
      "                     'totalWins': 4},\n",
      " 'Mega Scope Sway': {'Last Percentage': 25.00,\n",
      "                     'Popularity': 2.25,\n",
      "                     'Win Percentage': 25.00,\n",
      "                     'lostTo': {'8-Bit Audio': 1,\n",
      "                                'Keep Dodging': 1,\n",
      "                                'Keep Jumping': 1,\n",
      "                                'Melee Only': 1,\n",
      "                                'No Climbing/Jumping': 1,\n",
      "                                'No Triangle': 2,\n",
      "                                'Pdub It': 1,\n",
      "                                'Slow Motion': 1},\n",
      "                     'totalAppearances': 12,\n",
      "                     'totalLast': 3,\n",
      "                     'totalLosses': 9,\n",
      "                     'totalVotes': 27,\n",
      "                     'totalWins': 3},\n",
      " 'Melee Only': {'Last Percentage': 16.67,\n",
      "                'Popularity': 3.1666666666666665,\n",
      "                'Win Percentage': 66.67,\n",
      "                'lostTo': {'Keep Jumping': 1,\n",
      "                           'No Guns': 1,\n",
      "                           'Periodic Listen Mode': 1,\n",
      "                           'Pusher': 1},\n",
      "                'totalAppearances': 12,\n",
      "                'totalLast': 2,\n",
      "                'totalLosses': 4,\n",
      "                'totalVotes': 38,\n",
      "                'totalWins': 8},\n",
      " 'Mirror On Death': {'Last Percentage': 33.33,\n",
      "                     'Popularity': 1.5333333333333334,\n",
      "                     'Win Percentage': 26.67,\n",
      "                     'lostTo': {'Controller Mirror': 1,\n",
      "                                'Desk Pop': 1,\n",
      "                                'Graphic': 1,\n",
      "                                'Max Sensitivity': 1,\n",
      "                                'Melee Only': 1,\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "                                'No Crouch/Prone': 1,\n",
      "                                'No Guns': 1,\n",
      "                                'Sepia': 1,\n",
      "                                'Vintage': 1,\n",
      "                                'Water Color': 1,\n",
      "                                'Xenon Audio': 1},\n",
      "                     'totalAppearances': 15,\n",
      "                     'totalLast': 5,\n",
      "                     'totalLosses': 11,\n",
      "                     'totalVotes': 23,\n",
      "                     'totalWins': 4},\n",
      " 'Mirror World': {'Last Percentage': 0.00,\n",
      "                  'Popularity': 5.555555555555555,\n",
      "                  'Win Percentage': 88.89,\n",
      "                  'lostTo': {'Water Color': 1},\n",
      "                  'totalAppearances': 9,\n",
      "                  'totalLast': 0,\n",
      "                  'totalLosses': 1,\n",
      "                  'totalVotes': 50,\n",
      "                  'totalWins': 8},\n",
      " 'Moonlight': {'Last Percentage': 33.33,\n",
      "               'Popularity': 1.9444444444444444,\n",
      "               'Win Percentage': 33.33,\n",
      "               'lostTo': {'Disable Right Joystick': 1,\n",
      "                          'Disco': 2,\n",
      "                          'Infinite Ammo': 1,\n",
      "                          'Infinite Breath': 1,\n",
      "                          'No Melee': 1,\n",
      "                          'No Scoping': 1,\n",
      "                          'One Shot': 1,\n",
      "                          'Periodic Listen Mode': 2,\n",
      "                          'Vibrant': 1,\n",
      "                          'Xenon Audio': 1},\n",
      "               'totalAppearances': 18,\n",
      "               'totalLast': 6,\n",
      "               'totalLosses': 12,\n",
      "               'totalVotes': 35,\n",
      "               'totalWins': 6},\n",
      " 'Nascar': {'Last Percentage': 18.18,\n",
      "            'Popularity': 3.8181818181818183,\n",
      "            'Win Percentage': 63.64,\n",
      "            'lostTo': {'Controller Mirror': 1,\n",
      "                       'Drunk': 1,\n",
      "                       'No Guns': 1,\n",
      "                       'Toss A Molly': 1},\n",
      "            'totalAppearances': 11,\n",
      "            'totalLast': 2,\n",
      "            'totalLosses': 4,\n",
      "            'totalVotes': 42,\n",
      "            'totalWins': 7},\n",
      " 'No Aiming': {'Last Percentage': 18.18,\n",
      "               'Popularity': 3.090909090909091,\n",
      "               'Win Percentage': 54.55,\n",
      "               'lostTo': {'Chuck Smoke Bomb': 1,\n",
      "                          'Desk Pop': 1,\n",
      "                          'Large HUD': 1,\n",
      "                          'Nascar': 1,\n",
      "                          'Terminated': 1},\n",
      "               'totalAppearances': 11,\n",
      "               'totalLast': 2,\n",
      "               'totalLosses': 5,\n",
      "               'totalVotes': 34,\n",
      "               'totalWins': 6},\n",
      " 'No Climbing/Jumping': {'Last Percentage': 9.09,\n",
      "                         'Popularity': 2.727272727272727,\n",
      "                         'Win Percentage': 36.36,\n",
      "                         'lostTo': {'Disco': 1,\n",
      "                                    'Lock On Aim': 1,\n",
      "                                    'No Melee': 1,\n",
      "                                    'Toss A Molly': 1,\n",
      "                                    'Trinity': 1,\n",
      "                                    'Vibrant': 1,\n",
      "                                    'Vintage': 1},\n",
      "                         'totalAppearances': 11,\n",
      "                         'totalLast': 1,\n",
      "                         'totalLosses': 7,\n",
      "                         'totalVotes': 30,\n",
      "                         'totalWins': 4},\n",
      " 'No Crouch/Prone': {'Last Percentage': 27.78,\n",
      "                     'Popularity': 2.9444444444444446,\n",
      "                     'Win Percentage': 55.56,\n",
      "                     'lostTo': {'Controller Mirror': 1,\n",
      "                                'Dungeon': 1,\n",
      "                                'Helium Audio': 1,\n",
      "                                'Keep Jumping': 1,\n",
      "                                'One Shot': 1,\n",
      "                                'Toss A Molly': 1,\n",
      "                                'Trinity': 2},\n",
      "                     'totalAppearances': 18,\n",
      "                     'totalLast': 5,\n",
      "                     'totalLosses': 8,\n",
      "                     'totalVotes': 53,\n",
      "                     'totalWins': 10},\n",
      " 'No Guns': {'Last Percentage': 9.09,\n",
      "             'Popularity': 3.272727272727273,\n",
      "             'Win Percentage': 63.64,\n",
      "             'lostTo': {'Disable Right Joystick': 1,\n",
      "                        'Inverted': 1,\n",
      "                        'No Triangle': 1,\n",
      "                        'Pdub It': 1},\n",
      "             'totalAppearances': 11,\n",
      "             'totalLast': 1,\n",
      "             'totalLosses': 4,\n",
      "             'totalVotes': 36,\n",
      "             'totalWins': 7},\n",
      " 'No Melee': {'Last Percentage': 38.46,\n",
      "              'Popularity': 2.1538461538461537,\n",
      "              'Win Percentage': 30.77,\n",
      "              'lostTo': {'Blacklight': 1,\n",
      "                         'Blorange': 1,\n",
      "                         'Force Prone': 1,\n",
      "                         'Infinite Ammo': 1,\n",
      "                         'Inverted': 1,\n",
      "                         'No Guns': 1,\n",
      "                         'No Reloading': 1,\n",
      "                         'Pdub It': 1,\n",
      "                         'Rachy Flail': 1},\n",
      "              'totalAppearances': 13,\n",
      "              'totalLast': 5,\n",
      "              'totalLosses': 9,\n",
      "              'totalVotes': 28,\n",
      "              'totalWins': 4},\n",
      " 'No Reloading': {'Last Percentage': 27.78,\n",
      "                  'Popularity': 2.7222222222222223,\n",
      "                  'Win Percentage': 38.89,\n",
      "                  'lostTo': {'Chuck Smoke Bomb': 1,\n",
      "                             'Disable Right Joystick': 1,\n",
      "                             'Force Running': 1,\n",
      "                             'Headache': 1,\n",
      "                             'High Contrast Display': 1,\n",
      "                             'Lock On Aim': 1,\n",
      "                             'No Reticle': 1,\n",
      "                             'No Throwables': 1,\n",
      "                             'Restart Checkpoint': 1,\n",
      "                             'Vibrant': 1,\n",
      "                             'Xenon Audio': 1},\n",
      "                  'totalAppearances': 18,\n",
      "                  'totalLast': 5,\n",
      "                  'totalLosses': 11,\n",
      "                  'totalVotes': 49,\n",
      "                  'totalWins': 7},\n",
      " 'No Reticle': {'Last Percentage': 0.00,\n",
      "                'Popularity': 2.6153846153846154,\n",
      "                'Win Percentage': 30.77,\n",
      "                'lostTo': {'Blacklight': 1,\n",
      "                           'Bullet Speed': 1,\n",
      "                           'Chuck Smoke Bomb': 1,\n",
      "                           'Desk Pop': 1,\n",
      "                           'Disco': 1,\n",
      "                           'Mirror World': 1,\n",
      "                           'Moonlight': 1,\n",
      "                           'Noir': 1,\n",
      "                           'Periodic Listen Mode': 1},\n",
      "                'totalAppearances': 13,\n",
      "                'totalLast': 0,\n",
      "                'totalLosses': 9,\n",
      "                'totalVotes': 34,\n",
      "                'totalWins': 4},\n",
      " 'No Run/Dodge': {'Last Percentage': 50.00,\n",
      "                  'Popularity': 2.0,\n",
      "                  'Win Percentage': 12.50,\n",
      "                  'lostTo': {'Blood': 1,\n",
      "                             'Disco': 1,\n",
      "                             'Drunk': 1,\n",
      "                             'Mirror On Death': 1,\n",
      "                             'No Reticle': 1,\n",
      "                             'No Triangle': 1,\n",
      "                             'Pdub It': 1},\n",
      "                  'totalAppearances': 8,\n",
      "                  'totalLast': 4,\n",
      "                  'totalLosses': 7,\n",
      "                  'totalVotes': 16,\n",
      "                  'totalWins': 1},\n",
      " 'No Scoping': {'Last Percentage': 57.14,\n",
      "                'Popularity': 1.2857142857142858,\n",
      "                'Win Percentage': 7.14,\n",
      "                'lostTo': {'8-Bit': 1,\n",
      "                           'Afterlife': 1,\n",
      "                           'Beasts': 1,\n",
      "                           'Bullet Speed': 1,\n",
      "                           'Disable Right Joystick': 1,\n",
      "                           'Drug Zone': 1,\n",
      "                           'Headache': 1,\n",
      "                           'Helium Audio': 1,\n",
      "                           'Infinite Ammo': 2,\n",
      "                           'No Melee': 1,\n",
      "                           'Toss A Molly': 2},\n",
      "                'totalAppearances': 14,\n",
      "                'totalLast': 8,\n",
      "                'totalLosses': 13,\n",
      "                'totalVotes': 18,\n",
      "                'totalWins': 1},\n",
      " 'No Shoulder Swap': {'Last Percentage': 53.33,\n",
      "                      'Popularity': 0.6666666666666666,\n",
      "                      'Win Percentage': 0.00,\n",
      "                      'lostTo': {'8-Bit Audio': 1,\n",
      "                                 'Bullet Speed': 1,\n",
      "                                 'Controller Mirror': 1,\n",
      "                                 'Disable Right Joystick': 1,\n",
      "                                 'Force Running': 1,\n",
      "                                 'Gridlocked': 1,\n",
      "                                 'Infinite Ammo': 1,\n",
      "                                 'Melee Only': 1,\n",
      "                                 'Periodic Listen Mode': 1,\n",
      "                                 'Reduced Enemy Accuracy': 1,\n",
      "                                 'Slow Motion': 2,\n",
      "                                 'Traversal Audio Cues': 1,\n",
      "                                 'Vintage': 2},\n",
      "                      'totalAppearances': 15,\n",
      "                      'totalLast': 8,\n",
      "                      'totalLosses': 15,\n",
      "                      'totalVotes': 10,\n",
      "                      'totalWins': 0},\n",
      " 'No Throwables': {'Last Percentage': 12.50,\n",
      "                   'Popularity': 2.625,\n",
      "                   'Win Percentage': 37.50,\n",
      "                   'lostTo': {'Auto Pick-Up': 1,\n",
      "                              'Disco': 1,\n",
      "                              'Infinite Ammo': 1,\n",
      "                              'Keep Jumping': 1,\n",
      "                              'Melee Only': 1},\n",
      "                   'totalAppearances': 8,\n",
      "                   'totalLast': 1,\n",
      "                   'totalLosses': 5,\n",
      "                   'totalVotes': 21,\n",
      "                   'totalWins': 3},\n",
      " 'No Triangle': {'Last Percentage': 8.33,\n",
      "                 'Popularity': 3.4166666666666665,\n",
      "                 'Win Percentage': 58.33,\n",
      "                 'lostTo': {'Blacklight': 2,\n",
      "                            'Chuck Smoke Bomb': 1,\n",
      "                            'Helium Audio': 1,\n",
      "                            'Inverted': 1},\n",
      "                 'totalAppearances': 12,\n",
      "                 'totalLast': 1,\n",
      "                 'totalLosses': 5,\n",
      "                 'totalVotes': 41,\n",
      "                 'totalWins': 7},\n",
      " 'Noir': {'Last Percentage': 30.77,\n",
      "          'Popularity': 2.4615384615384617,\n",
      "          'Win Percentage': 46.15,\n",
      "          'lostTo': {'Chuck Smoke Bomb': 1,\n",
      "                     'Disco': 1,\n",
      "                     'Keep Dodging': 1,\n",
      "                     'Mirror World': 1,\n",
      "                     'No Guns': 1,\n",
      "                     'One Shot': 1,\n",
      "                     'Touch Of Death': 1},\n",
      "          'totalAppearances': 13,\n",
      "          'totalLast': 4,\n",
      "          'totalLosses': 7,\n",
      "          'totalVotes': 32,\n",
      "          'totalWins': 6},\n",
      " 'One Shot': {'Last Percentage': 33.33,\n",
      "              'Popularity': 2.2222222222222223,\n",
      "              'Win Percentage': 22.22,\n",
      "              'lostTo': {'CTG Strat': 1,\n",
      "                         'Force Prone': 1,\n",
      "                         'Inferno': 3,\n",
      "                         'Moonlight': 1,\n",
      "                         'Nascar': 1,\n",
      "                         'No Climbing/Jumping': 1,\n",
      "                         'No Crouch/Prone': 1,\n",
      "                         'No Guns': 1,\n",
      "                         'No Triangle': 2,\n",
      "                         'Swap Joysticks': 1,\n",
      "                         'Terminated': 1},\n",
      "              'totalAppearances': 18,\n",
      "              'totalLast': 6,\n",
      "              'totalLosses': 14,\n",
      "              'totalVotes': 40,\n",
      "              'totalWins': 4},\n",
      " 'Pdub It': {'Last Percentage': 26.67,\n",
      "             'Popularity': 3.2,\n",
      "             'Win Percentage': 46.67,\n",
      "             'lostTo': {'Bullet Speed': 1,\n",
      "                        'Headache': 1,\n",
      "                        'Helium Audio': 1,\n",
      "                        'High Contrast Display': 1,\n",
      "                        'Infinite Ammo': 1,\n",
      "                        'Mirror On Death': 1,\n",
      "                        'No Guns': 1,\n",
      "                        'Xenon Audio': 1},\n",
      "             'totalAppearances': 15,\n",
      "             'totalLast': 4,\n",
      "             'totalLosses': 8,\n",
      "             'totalVotes': 48,\n",
      "             'totalWins': 7},\n",
      " 'Periodic Listen Mode': {'Last Percentage': 37.50,\n",
      "                          'Popularity': 2.0625,\n",
      "                          'Win Percentage': 50.00,\n",
      "                          'lostTo': {'CTG Strat': 1,\n",
      "                                     'Disable Right Joystick': 1,\n",
      "                                     'Disco': 1,\n",
      "                                     'Drunk': 2,\n",
      "                                     'Rachy Flail': 1,\n",
      "                                     'Restart Checkpoint': 1,\n",
      "                                     'Traversal Audio Cues': 1},\n",
      "                          'totalAppearances': 16,\n",
      "                          'totalLast': 6,\n",
      "                          'totalLosses': 8,\n",
      "                          'totalVotes': 33,\n",
      "                          'totalWins': 8},\n",
      " 'Pop Poster': {'Last Percentage': 21.43,\n",
      "                'Popularity': 2.357142857142857,\n",
      "                'Win Percentage': 21.43,\n",
      "                'lostTo': {'Auto Pick-Up': 1,\n",
      "                           'Controller Mirror': 1,\n",
      "                           'Desk Pop': 2,\n",
      "                           'Disco': 1,\n",
      "                           'Fire': 1,\n",
      "                           'Force Prone': 1,\n",
      "                           'Force Running': 1,\n",
      "                           'Gridlocked': 1,\n",
      "                           'Inverted': 1,\n",
      "                           'No Melee': 1},\n",
      "                'totalAppearances': 14,\n",
      "                'totalLast': 3,\n",
      "                'totalLosses': 11,\n",
      "                'totalVotes': 33,\n",
      "                'totalWins': 3},\n",
      " 'Pusher': {'Last Percentage': 70.00,\n",
      "            'Popularity': 1.7,\n",
      "            'Win Percentage': 20.00,\n",
      "            'lostTo': {'Bullet Speed': 1,\n",
      "                       'Infinite Ammo': 1,\n",
      "                       'Large HUD': 1,\n",
      "                       'Mega Scope Sway': 1,\n",
      "                       'Melee Only': 1,\n",
      "                       'No Crouch/Prone': 1,\n",
      "                       'Sepia': 1,\n",
      "                       'Slow Motion': 1},\n",
      "            'totalAppearances': 10,\n",
      "            'totalLast': 7,\n",
      "            'totalLosses': 8,\n",
      "            'totalVotes': 17,\n",
      "            'totalWins': 2},\n",
      " 'Rachy Flail': {'Last Percentage': 16.67,\n",
      "                 'Popularity': 3.8333333333333335,\n",
      "                 'Win Percentage': 58.33,\n",
      "                 'lostTo': {'CTG Strat': 1,\n",
      "                            'Disable Right Joystick': 1,\n",
      "                            'Infinite Crafting': 1,\n",
      "                            'Inverted': 1,\n",
      "                            'Melee Only': 1},\n",
      "                 'totalAppearances': 12,\n",
      "                 'totalLast': 2,\n",
      "                 'totalLosses': 5,\n",
      "                 'totalVotes': 46,\n",
      "                 'totalWins': 7},\n",
      " 'Reduced Enemy Accuracy': {'Last Percentage': 69.23,\n",
      "                            'Popularity': 0.7692307692307693,\n",
      "                            'Win Percentage': 7.69,\n",
      "                            'lostTo': {'4-Bit Audio': 1,\n",
      "                                       'Afterlife': 1,\n",
      "                                       'Auto Pick-Up': 1,\n",
      "                                       'Beasts': 1,\n",
      "                                       'Drunk': 1,\n",
      "                                       'Fire': 1,\n",
      "                                       'Inferno': 1,\n",
      "                                       'Moonlight': 1,\n",
      "                                       'Nascar': 1,\n",
      "                                       'No Guns': 1,\n",
      "                                       'Periodic Listen Mode': 1,\n",
      "                                       'Rachy Flail': 1},\n",
      "                            'totalAppearances': 13,\n",
      "                            'totalLast': 9,\n",
      "                            'totalLosses': 12,\n",
      "                            'totalVotes': 10,\n",
      "                            'totalWins': 1},\n",
      " 'Reduced Enemy Perception': {'Last Percentage': 50.00,\n",
      "                              'Popularity': 0.6666666666666666,\n",
      "                              'Win Percentage': 0.00,\n",
      "                              'lostTo': {'1960': 1,\n",
      "                                         '8-Bit Audio': 1,\n",
      "                                         'Headache': 1,\n",
      "                                         'Inferno': 1,\n",
      "                                         'Inverted': 1,\n",
      "                                         'Melee Only': 1,\n",
      "                                         'Mirror On Death': 1,\n",
      "                                         'Moonlight': 1,\n",
      "                                         'Noir': 1,\n",
      "                                         'Periodic Listen Mode': 1,\n",
      "                                         'Restart Checkpoint': 1,\n",
      "                                         'Slow Motion': 1},\n",
      "                              'totalAppearances': 12,\n",
      "                              'totalLast': 6,\n",
      "                              'totalLosses': 12,\n",
      "                              'totalVotes': 8,\n",
      "                              'totalWins': 0},\n",
      " 'Restart Checkpoint': {'Last Percentage': 12.50,\n",
      "                        'Popularity': 3.75,\n",
      "                        'Win Percentage': 50.00,\n",
      "                        'lostTo': {'Drunk': 1,\n",
      "                                   'High Contrast Display': 1,\n",
      "                                   'Mirror On Death': 1,\n",
      "                                   'Pdub It': 1},\n",
      "                        'totalAppearances': 8,\n",
      "                        'totalLast': 1,\n",
      "                        'totalLosses': 4,\n",
      "                        'totalVotes': 30,\n",
      "                        'totalWins': 4},\n",
      " 'Sepia': {'Last Percentage': 45.45,\n",
      "           'Popularity': 1.8181818181818181,\n",
      "           'Win Percentage': 18.18,\n",
      "           'lostTo': {'8-Bit Audio': 1,\n",
      "                      'Helium Audio': 1,\n",
      "                      'Lock On Aim': 1,\n",
      "                      'Mirror World': 1,\n",
      "                      'Nascar': 1,\n",
      "                      'No Crouch/Prone': 1,\n",
      "                      'No Triangle': 1,\n",
      "                      'One Shot': 1,\n",
      "                      'Xenon Audio': 1},\n",
      "           'totalAppearances': 11,\n",
      "           'totalLast': 5,\n",
      "           'totalLosses': 9,\n",
      "           'totalVotes': 20,\n",
      "           'totalWins': 2},\n",
      " 'Slow Motion': {'Last Percentage': 30.00,\n",
      "                 'Popularity': 2.9,\n",
      "                 'Win Percentage': 40.00,\n",
      "                 'lostTo': {'CTG Strat': 1,\n",
      "                            'Disable Right Joystick': 1,\n",
      "                            'Force Prone': 1,\n",
      "                            'No Aiming': 1,\n",
      "                            'Noir': 1,\n",
      "                            'Xenon Audio': 1},\n",
      "                 'totalAppearances': 10,\n",
      "                 'totalLast': 3,\n",
      "                 'totalLosses': 6,\n",
      "                 'totalVotes': 29,\n",
      "                 'totalWins': 4},\n",
      " 'Swap Joysticks': {'Last Percentage': 12.50,\n",
      "                    'Popularity': 3.125,\n",
      "                    'Win Percentage': 75.00,\n",
      "                    'lostTo': {'Keep Dodging': 1, 'Mirror World': 1},\n",
      "                    'totalAppearances': 8,\n",
      "                    'totalLast': 1,\n",
      "                    'totalLosses': 2,\n",
      "                    'totalVotes': 25,\n",
      "                    'totalWins': 6},\n",
      " 'Terminated': {'Last Percentage': 42.11,\n",
      "                'Popularity': 1.5789473684210527,\n",
      "                'Win Percentage': 26.32,\n",
      "                'lostTo': {'Blacklight': 1,\n",
      "                           'Bullet Speed': 2,\n",
      "                           'Desk Pop': 1,\n",
      "                           'Disco': 1,\n",
      "                           'Large HUD': 1,\n",
      "                           'Melee Only': 1,\n",
      "                           'Nascar': 1,\n",
      "                           'No Melee': 1,\n",
      "                           'No Reloading': 1,\n",
      "                           'No Run/Dodge': 1,\n",
      "                           'Periodic Listen Mode': 1,\n",
      "                           'Rachy Flail': 1,\n",
      "                           'Xenon Audio': 1},\n",
      "                'totalAppearances': 19,\n",
      "                'totalLast': 8,\n",
      "                'totalLosses': 14,\n",
      "                'totalVotes': 30,\n",
      "                'totalWins': 5},\n",
      " 'Toss A Molly': {'Last Percentage': 16.67,\n",
      "                  'Popularity': 4.333333333333333,\n",
      "                  'Win Percentage': 83.33,\n",
      "                  'lostTo': {'Controller Mirror': 1},\n",
      "                  'totalAppearances': 6,\n",
      "                  'totalLast': 1,\n",
      "                  'totalLosses': 1,\n",
      "                  'totalVotes': 26,\n",
      "                  'totalWins': 5},\n",
      " 'Touch Of Death': {'Last Percentage': 25.00,\n",
      "                    'Popularity': 2.25,\n",
      "                    'Win Percentage': 37.50,\n",
      "                    'lostTo': {'Force Running': 1,\n",
      "                               'Keep Dodging': 1,\n",
      "                               'No Scoping': 1,\n",
      "                               'Toss A Molly': 1,\n",
      "                               'Warm': 1},\n",
      "                    'totalAppearances': 8,\n",
      "                    'totalLast': 2,\n",
      "                    'totalLosses': 5,\n",
      "                    'totalVotes': 18,\n",
      "                    'totalWins': 3},\n",
      " 'Traversal Assistance': {'Last Percentage': 64.71,\n",
      "                          'Popularity': 0.5882352941176471,\n",
      "                          'Win Percentage': 0.00,\n",
      "                          'lostTo': {'1960': 1,\n",
      "                                     '4-Bit Audio': 1,\n",
      "                                     'Blacklight': 1,\n",
      "                                     'CTG Strat': 1,\n",
      "                                     'Desert Fog': 1,\n",
      "                                     'Inverted': 2,\n",
      "                                     'Keep Jumping': 2,\n",
      "                                     'Lock On Aim': 1,\n",
      "                                     'Mirror World': 1,\n",
      "                                     'No Crouch/Prone': 1,\n",
      "                                     'No Melee': 1,\n",
      "                                     'One Shot': 1,\n",
      "                                     'Pusher': 1,\n",
      "                                     'Rachy Flail': 1,\n",
      "                                     'Swap Joysticks': 1},\n",
      "                          'totalAppearances': 17,\n",
      "                          'totalLast': 11,\n",
      "                          'totalLosses': 17,\n",
      "                          'totalVotes': 10,\n",
      "                          'totalWins': 0},\n",
      " 'Traversal Audio Cues': {'Last Percentage': 75.00,\n",
      "                          'Popularity': 1.25,\n",
      "                          'Win Percentage': 12.50,\n",
      "                          'lostTo': {'Desk Pop': 1,\n",
      "                                     'Graphic': 1,\n",
      "                                     'Headache': 1,\n",
      "                                     'Mirror World': 1,\n",
      "                                     'No Climbing/Jumping': 1,\n",
      "                                     'No Reticle': 1,\n",
      "                                     'Swap Joysticks': 1},\n",
      "                          'totalAppearances': 8,\n",
      "                          'totalLast': 6,\n",
      "                          'totalLosses': 7,\n",
      "                          'totalVotes': 10,\n",
      "                          'totalWins': 1},\n",
      " 'Trinity': {'Last Percentage': 50.00,\n",
      "             'Popularity': 1.3333333333333333,\n",
      "             'Win Percentage': 22.22,\n",
      "             'lostTo': {'Afterlife': 1,\n",
      "                        'Bullet Speed': 1,\n",
      "                        'Chuck Smoke Bomb': 2,\n",
      "                        'Controller Mirror': 1,\n",
      "                        'Desk Pop': 1,\n",
      "                        'Dungeon': 1,\n",
      "                        'Headache': 1,\n",
      "                        'Helium Audio': 1,\n",
      "                        'Inverted': 1,\n",
      "                        'Keep Dodging': 1,\n",
      "                        'No Aiming': 1,\n",
      "                        'No Melee': 1,\n",
      "                        'Xenon Audio': 1},\n",
      "             'totalAppearances': 18,\n",
      "             'totalLast': 9,\n",
      "             'totalLosses': 14,\n",
      "             'totalVotes': 24,\n",
      "             'totalWins': 4},\n",
      " 'Vibrant': {'Last Percentage': 40.00,\n",
      "             'Popularity': 1.9,\n",
      "             'Win Percentage': 30.00,\n",
      "             'lostTo': {'8-Bit': 1,\n",
      "                        'Graphic': 1,\n",
      "                        'Infinite Crafting': 1,\n",
      "                        'Keep Jumping': 1,\n",
      "                        'Melee Only': 1,\n",
      "                        'Terminated': 1,\n",
      "                        'Vintage': 1},\n",
      "             'totalAppearances': 10,\n",
      "             'totalLast': 4,\n",
      "             'totalLosses': 7,\n",
      "             'totalVotes': 19,\n",
      "             'totalWins': 3},\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      " 'Vintage': {'Last Percentage': 36.36,\n",
      "             'Popularity': 2.1818181818181817,\n",
      "             'Win Percentage': 27.27,\n",
      "             'lostTo': {'Blacklight': 1,\n",
      "                        'Blorange': 1,\n",
      "                        'Infinite Crafting': 1,\n",
      "                        'Keep Jumping': 1,\n",
      "                        'Mirror World': 1,\n",
      "                        'No Crouch/Prone': 1,\n",
      "                        'Rachy Flail': 1,\n",
      "                        'Water Color': 1},\n",
      "             'totalAppearances': 11,\n",
      "             'totalLast': 4,\n",
      "             'totalLosses': 8,\n",
      "             'totalVotes': 24,\n",
      "             'totalWins': 3},\n",
      " 'Void': {'Last Percentage': 30.77,\n",
      "          'Popularity': 1.5384615384615385,\n",
      "          'Win Percentage': 7.69,\n",
      "          'lostTo': {'CTG Strat': 1,\n",
      "                     'Disco': 1,\n",
      "                     'Gridlocked': 1,\n",
      "                     'High Contrast Display': 1,\n",
      "                     'Infinite Crafting': 1,\n",
      "                     'Max Sensitivity': 1,\n",
      "                     'Mirror World': 1,\n",
      "                     'No Aiming': 2,\n",
      "                     'No Reloading': 1,\n",
      "                     'Pdub It': 1,\n",
      "                     'Touch Of Death': 1},\n",
      "          'totalAppearances': 13,\n",
      "          'totalLast': 4,\n",
      "          'totalLosses': 12,\n",
      "          'totalVotes': 20,\n",
      "          'totalWins': 1},\n",
      " 'Warm': {'Last Percentage': 53.85,\n",
      "          'Popularity': 0.9230769230769231,\n",
      "          'Win Percentage': 7.69,\n",
      "          'lostTo': {'Bullet Speed': 1,\n",
      "                     'CTG Strat': 1,\n",
      "                     'Drunk': 1,\n",
      "                     'Large HUD': 1,\n",
      "                     'Mega Scope Sway': 1,\n",
      "                     'No Aiming': 3,\n",
      "                     'No Crouch/Prone': 1,\n",
      "                     'No Guns': 1,\n",
      "                     'No Reloading': 1,\n",
      "                     'Periodic Listen Mode': 1},\n",
      "          'totalAppearances': 13,\n",
      "          'totalLast': 7,\n",
      "          'totalLosses': 12,\n",
      "          'totalVotes': 12,\n",
      "          'totalWins': 1},\n",
      " 'Water Color': {'Last Percentage': 42.86,\n",
      "                 'Popularity': 1.8571428571428572,\n",
      "                 'Win Percentage': 28.57,\n",
      "                 'lostTo': {'Helium Audio': 1,\n",
      "                            'Moonlight': 1,\n",
      "                            'Nascar': 1,\n",
      "                            'No Triangle': 1,\n",
      "                            'Xenon Audio': 1},\n",
      "                 'totalAppearances': 7,\n",
      "                 'totalLast': 3,\n",
      "                 'totalLosses': 5,\n",
      "                 'totalVotes': 13,\n",
      "                 'totalWins': 2},\n",
      " 'Xenon Audio': {'Last Percentage': 23.08,\n",
      "                 'Popularity': 2.6153846153846154,\n",
      "                 'Win Percentage': 46.15,\n",
      "                 'lostTo': {'8-Bit': 1,\n",
      "                            'Controller Mirror': 1,\n",
      "                            'Disco': 1,\n",
      "                            'Mega Scope Sway': 1,\n",
      "                            'Noir': 1,\n",
      "                            'Rachy Flail': 1,\n",
      "                            'Restart Checkpoint': 1},\n",
      "                 'totalAppearances': 13,\n",
      "                 'totalLast': 3,\n",
      "                 'totalLosses': 7,\n",
      "                 'totalVotes': 34,\n",
      "                 'totalWins': 6}}\n"
     ]
    }
   ],
   "source": [
    "pp.pprint( voteData )"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
